# Site Metadata Settings
title: Omni
keywords: >
  storage, self-storage, moving, boxes, delivery, on-demand, home, organize, organization, 
  closet, container, concierge, amenity, residential, building, high-rise, front desk, San Francisco, 
  SF, CA, California
description: > 
  Convenient on-demand storage. On-premise pickup and delivery. 
  No minimums or contracts. Mobile app with visual catalog of every 
  item you store.
image: "share-image.jpg"

# Social Settings
email: hello@beomni.com
twitter: beomni
instagram: beomni
medium: "omni-blog"
facebook_app_id: 910785135655711
apple_app_id: 1039456090

# Misc. Settings
baseurl: ""
url: "https://local.beomni.com"
homepage: "https://www.beomni.com"

sass:
    sass_dir: vendor

# Region List
defaults:
    -
        scope:
          path: ""
          type: pages
        values:          
            section_2_subheader: "Want to avoid self storage? Omni can help!"
            section_3_subheader: "Neighborhood spots we dig"
            section_4_subheader: "Check out some of our residential building partners"
    -
        scope:
            path: "san-francisco"
            type: pages
        values:
            image: 'regions/san-francisco/index.jpg'
            title: "San Francisco"
            layout: neighborhood
            description: >
              San Francisco has quickly become one of the global centers of technology and entrepreneurialism, drawing tens
              of thousands of new residents in the last few years alone—it’s now the second-most densely populated city in
              America (New York faithfully remains #1). One of the most attractive parts of SF living is the unique
              combination of scenery, climate, and culture, enabling San Franciscans to pursue a limitless variety of
              adventures in their spare time: Surf, snow, mountains, trails, vineyards, farms, and world-class golf resorts
              are all within a few hours’ drive. </p>
              <p>As new housing developments open and price-per-square-foot continues to soar, residents both new and long
              -established are compromising on many (many!) things – space to live their lives is one of them. Being able
              to stretch out at home and quiet your mind after a long day is a crucial for one’s sanity, but becomes harder
              to do when you’re co-existing with a lifetime of stuff in a small space. Taking advantage of all the area has
              to offer requires some equipment, but who wants to use their living room as a defacto garage for lack of
              storage? Sure, you might love your skis and your bike, but if you had the choice, would you want them to be
              part of the ambiance in your bedroom?</p>
              <p>Self storage in SF is expensive, hard to visit, and not convenient to most neighborhoods where space is
              tight – not to mention that once you exile your stuff and make the trip to your unit, you’re stuck rummaging 
              through boxes to find the one thing you might need… or even worse, you forget what’s in there altogether. 
              Your stuff becomes a mystery. You stop using it. You’re paying rent to give your things their own apartment, 
              in effect.</p>
              <p>Omni wants to help San Franciscans live lighter, reclaim their living space, and still having access to 
              the things they love but don’t need every day. We’re the walk-in closet you don’t have at home, the garage 
              you once used growing up, and the full-service concierge for your stuff.</p>

            section_1_header: "San Francisco"
            section_2_header: "Need more space in San Francisco?"
            section_3_header: "Omni Picks in San Francisco"
            section_4_header: "Looking to live in San Francisco?"
