# Site Metadata Settings
title: Omni
keywords: >
  storage, self-storage, moving, boxes, delivery, on-demand, home, organize, organization, 
  closet, container, concierge, amenity, residential, building, high-rise, front desk, San Francisco, 
  SF, CA, California
description: > 
  Convenient on-demand storage. On-premise pickup and delivery. 
  No minimums or contracts. Mobile app with visual catalog of every 
  item you store.
image: "https://www.beomni.com/img/share-image.jpg"

# Social Settings
email: hello@beomni.com
twitter: beomni
instagram: beomni
medium: "omni-blog"
facebook_app_id: 910785135655711
apple_app_id: 1039456090

# Misc. Settings
baseurl: ""
url: "http://local.beomni.com"
homepage: "https://www.beomni.com"

# Region List
defaults:
	-
		scope:
			path: "san-francisco"
			type: pages
		values:
			title: "Omni | San Francisco"
			label: "San Francisco"
			layout: neighborhood
	  